### ISSUE TITLE
No Commented Code

### ISSUE THREAD

**Issue by nguyen-b** [OASTEM/Rapid-React-2022#4]
Remove all commented code:

https://github.com/OASTEM/Rapid-React-2022/blob/32054d1818b4a4878e84290b4bf15184e42254bc/src/main/java/frc/robot/LogitechGamingPad.java#L370-L396

https://github.com/OASTEM/Rapid-React-2022/blob/32054d1818b4a4878e84290b4bf15184e42254bc/src/main/java/frc/robot/LogitechGamingPad.java#L409-L439

https://github.com/OASTEM/Rapid-React-2022/blob/32054d1818b4a4878e84290b4bf15184e42254bc/src/main/java/frc/robot/LogitechGamingPad.java#L466-L476

https://github.com/OASTEM/Rapid-React-2022/blob/32054d1818b4a4878e84290b4bf15184e42254bc/src/main/java/frc/robot/LogitechGamingPad.java#L501-L511

**Comment by jyue86** [comment]
Can I also delete the last 3 methods? They're currently not implemented, and I don't expect them to be useful in the future. 

https://github.com/OASTEM/Rapid-React-2022/blob/32054d1818b4a4878e84290b4bf15184e42254bc/src/main/java/frc/robot/LogitechGamingPad.java#L528-L539

Edit: And maybe these methods as well.

https://github.com/OASTEM/Rapid-React-2022/blob/32054d1818b4a4878e84290b4bf15184e42254bc/src/main/java/frc/robot/LogitechGamingPad.java#L513-L525

**Comment by nguyen-b** [comment]
@justinyue1643 I agree, we should delete methods that are useless.
